const products = [
  {
    id: 1,
    image: "/coat.webp",
    name: "The north coat",
    discount: "-40%",
    price: 120,
    oldPrice: 160,
    rating: 4,
    reviews: 88,
    isNew: false,
    stockStatus: "In Stock",
  },
  {
    id: 2,
    image: "/bag.webp",
    name: "Gucci duffle bag",
    discount: "-35%",
    price: 150,
    oldPrice: 260,
    rating: 4,
    reviews: 75,
    isNew: true,
    stockStatus: "Low Stock",
  },
  {
    id: 3,
    image: "/headphones.webp",
    name: "RGB liquid CPU Cooler",
    discount: "-30%",
    price: 370,
    oldPrice: 400,
    rating: 5,
    reviews: 99,
    isNew: false,
    stockStatus: "In Stock",
  },
  {
    id: 4,
    image: "/bookshelf.webp",
    name: "Small BookSelf",
    discount: "-25%",
    price: 375,
    oldPrice: 400,
    rating: 4,
    reviews: 58,
    isNew: false,
    stockStatus: "In Stock",
  },
  {
    id: 5,
    image: "/chair.webp",
    name: "S-Series Comfort Chair",
    discount: "-25%",
    price: 375,
    oldPrice: 400,
    rating: 4,
    reviews: 58,
    isNew: true,
    stockStatus: "In Stock",
  },
  {
    id: 6,
    image: "/playstation.webp",
    name: "PlayStation 5",
    discount: "-15%",
    price: 499,
    oldPrice: 590,
    rating: 5,
    reviews: 120,
    isNew: true,
    stockStatus: "In Stock",
    category: "gaming",
  },
  {
    id: 7,
    image: "/womenCollections.webp",
    name: "Women's Collections",
    discount: "-20%",
    price: 199,
    oldPrice: 249,
    rating: 4,
    reviews: 98,
    isNew: true,
    stockStatus: "In Stock",
  },
  {
    id: 8,
    image: "/speakers.webp",
    name: "Amazon Wireless Speakers",
    discount: "-10%",
    price: 99,
    oldPrice: 110,
    rating: 4,
    reviews: 45,
    isNew: false,
    stockStatus: "Low Stock",
  },
  {
    id: 9,
    image: "/perfume.webp",
    name: "GUCCI INTENSE OUD EDP",
    discount: "-25%",
    price: 150,
    oldPrice: 200,
    rating: 5,
    reviews: 62,
    isNew: false,
    stockStatus: "In Stock",
  },
  {
    id: 10,
    image: "/JBL_BOOMBOX.webp",
    name: "JBL_BOOMBOX",
    discount: "-25%",
    price: 150,
    oldPrice: 200,
    rating: 5,
    reviews: 62,
    isNew: false,
    stockStatus: "In Stock",
  },
  {
    id: 11,
    image: "/dogfood.webp",
    name: "Breed Dry Dog Food",
    discount: "-40%",
    price: 120,
    oldPrice: 160,
    rating: 4,
    reviews: 88,
    stockStatus: "In Stock",
    isNew: false,
    isBestseller: true,
  },
  {
    id: 12,
    image: "/camera.webp",
    name: "CANON EOS DSLR Camera",
    discount: "-35%",
    price: 150,
    oldPrice: 260,
    rating: 4,
    reviews: 75,
    stockStatus: "Low Stock",
    isNew: true,
    isBestseller: false,
    category: "cameras",
  },
  {
    id: 13,
    image: "/laptop.webp",
    name: "ASUS FHD Gaming Laptop",
    discount: "-30%",
    price: 370,
    oldPrice: 400,
    rating: 5,
    reviews: 99,
    stockStatus: "In Stock",
    isNew: false,
    isBestseller: true,
    category: "computers",
  },
  {
    id: 14,
    image: "/cream.webp",
    name: "Curology Product Set",
    discount: "-25%",
    price: 375,
    oldPrice: 400,
    rating: 4,
    reviews: 58,
    stockStatus: "In Stock",
    isNew: true,
    isBestseller: false,
  },
  {
    id: 15,
    image: "/car.webp",
    name: "Kids Electric Car",
    discount: "-25%",
    price: 375,
    oldPrice: 400,
    rating: 4,
    reviews: 58,
    stockStatus: "In Stock",
    isNew: false,
    isBestseller: false,
  },
  {
    id: 16,
    image: "/shoes.webp",
    name: "Jr. Zoom Soccer Cleats",
    discount: "-25%",
    price: 375,
    oldPrice: 400,
    rating: 4,
    reviews: 58,
    stockStatus: "Low Stock",
    isNew: false,
    isBestseller: false,
  },
  {
    id: 17,
    image: "/g-black.webp",
    name: "GP11 Shooter USB Gamepad",
    discount: "-25%",
    price: 375,
    oldPrice: 400,
    rating: 4,
    reviews: 58,
    stockStatus: "In Stock",
    isNew: false,
    isBestseller: false,
    category: "gaming",
  },
  {
    id: 18,
    image: "/jacket.webp",
    name: "Quilted Satin Jacket",
    discount: "-25%",
    price: 375,
    oldPrice: 400,
    rating: 4,
    reviews: 58,
    stockStatus: "In Stock",
    isNew: true,
    isBestseller: false,
  },
  {
    id: 21,
    image: "/g-colored.webp",
    name: "HAVIT HV-G92 Gamepad",
    discount: "-40%",
    price: 120,
    oldPrice: 160,
    rating: 4,
    reviews: 88,
    isNew: false,
    stockStatus: "In Stock",
    category: "gaming",
  },
  {
    id: 22,
    image: "/keyboard.webp",
    name: "AK-900 Wired Keyboard",
    discount: "-35%",
    price: 950,
    oldPrice: 1160,
    rating: 4,
    reviews: 75,
    isNew: false,
    stockStatus: "In Stock",
    category: "computers",
  },
  {
    id: 23,
    image: "/tv.webp",
    name: "IPS LCD Gaming Monitor",
    discount: "-30%",
    price: 370,
    oldPrice: 400,
    rating: 5,
    reviews: 99,
    isNew: true,
    stockStatus: "In Stock",
    category: "gaming",
  },
  {
    id: 30,
    image: "/phone1.webp",
    name: "infinix Zero Ultra",
    discount: "-20%",
    price: 950,
    oldPrice: 1190,
    rating: 5,
    reviews: 142,
    isNew: true,
    stockStatus: "In Stock",
    category: "phones",
  },
  {
    id: 31,
    image:
      "/phone2.webp",
    name: "Samsung Galaxy Z ",
    discount: "-15%",
    price: 1250,
    oldPrice: 1470,
    rating: 5,
    reviews: 312,
    isNew: false,
    stockStatus: "In Stock",
    category: "phones",
  },
  {
    id: 32,
    image:
      "/phone3.webp",
    name: "Apple iPhone 14 Pro",
    discount: "-18%",
    price: 820,
    oldPrice: 1000,
    rating: 4,
    reviews: 98,
    isNew: false,
    stockStatus: "In Stock",
    category: "phones",
  },
  {
    id: 33,
    image:
      "/pc1.webp",
    name: "NVIDIA GeForce RTX 4090",
    discount: "-12%",
    price: 2200,
    oldPrice: 2500,
    rating: 5,
    reviews: 412,
    isNew: true,
    stockStatus: "In Stock",
    category: "computers",
  },
  {
    id: 34,
    image: "/pc2.webp",
    name: "AMD Radeon RX 7900 XTX",
    discount: "-10%",
    price: 1800,
    oldPrice: 2000,
    rating: 4,
    reviews: 285,
    isNew: false,
    stockStatus: "In Stock",
    category: "computers",
  },

  {
    id: 35,
    image: "/watch.webp",
    name: "Apple Watch Series 9",
    discount: "-15%",
    price: 399,
    oldPrice: 470,
    rating: 5,
    reviews: 198,
    isNew: true,
    stockStatus: "In Stock",
    category: "smartwatches",
  },
  {
    id: 36,
    image: "/watch1.webp",
    name: "Samsung Galaxy Watch 6",
    discount: "-20%",
    price: 299,
    oldPrice: 375,
    rating: 4,
    reviews: 112,
    isNew: false,
    stockStatus: "In Stock",
    category: "smartwatches",
  },
  {
    id: 37,
    image: "/watch2.webp",
    name: "Fitbit Versa 4",
    discount: "-18%",
    price: 169,
    oldPrice: 210,
    rating: 4,
    reviews: 76,
    isNew: true,
    stockStatus: "In Stock",
    category: "smartwatches",
  },
  {
    id: 38,
    image: "/camera1.webp",
    name: "Canon EOS 90D DSLR",
    discount: "-10%",
    price: 950,
    oldPrice: 1050,
    rating: 5,
    reviews: 182,
    isNew: true,
    stockStatus: "In Stock",
    category: "cameras",
  },
  {
    id: 39,
    image: "/camera3.webp",
    name: "Sony Alpha a7 III",
    discount: "-12%",
    price: 1199,
    oldPrice: 1350,
    rating: 4,
    reviews: 145,
    isNew: false,
    stockStatus: "In Stock",
    category: "cameras",
  },
  {
    id: 40,
    image: "/camera2.webp",
    name: "Nikon Z6 II Mirrorless",
    discount: "-15%",
    price: 1100,
    oldPrice: 1290,
    rating: 4,
    reviews: 102,
    isNew: false,
    stockStatus: "In Stock",
    category: "cameras",
  },
  {
    id: 41,
    image: "/headphone1.webp",
    name: "Sony WH-1000XM4",
    discount: "-25%",
    price: 300,
    oldPrice: 400,
    rating: 5,
    reviews: 450,
    isNew: true,
    stockStatus: "In Stock",
    category: "headphones",
  },
  {
    id: 42,
    image: "/headphone2.webp",
    name: "Bose QuietComfort 45",
    discount: "-20%",
    price: 280,
    oldPrice: 350,
    rating: 4,
    reviews: 315,
    isNew: false,
    stockStatus: "In Stock",
    category: "headphones",
  },
  {
    id: 43,
    image: "/headphone3.webp",
    name: "Apple AirPods Max",
    discount: "-15%",
    price: 490,
    oldPrice: 580,
    rating: 4,
    reviews: 220,
    isNew: false,
    stockStatus: "In Stock",
    category: "headphones",
  },
  {
    id: 44,
    image: "/gaming1.webp",
    name: "Razer BlackShark V2",
    discount: "-20%",
    price: 110,
    oldPrice: 137,
    rating: 5,
    reviews: 190,
    isNew: true,
    stockStatus: "In Stock",
    category: "gaming",
  },
  {
    id: 45,
    image: "/gaming2.webp",
    name: "Logitech G502 HERO",
    discount: "-18%",
    price: 45,
    oldPrice: 55,
    rating: 4,
    reviews: 250,
    isNew: false,
    stockStatus: "In Stock",
    category: "gaming",
  },
  {
    id: 46,
    image: "/gaming3.webp",
    name: "Redragon K552 Mechanical Keyboard",
    discount: "-30%",
    price: 60,
    oldPrice: 85,
    rating: 4,
    reviews: 312,
    isNew: false,
    stockStatus: "In Stock",
    category: "gaming",
  },
];

export default products;
