const productsData = {
  1: {
    id: 1,
    name: "The north coat",
    price: 120,
    oldPrice: 160,
    discount: "-40%",
    rating: 4,
    reviews: 88,
    description:
      "High-quality north face coat perfect for winter weather. Made with premium materials and designed for ultimate comfort and warmth.",
    images: [
      "/coat.webp",
      "/coat.webp", 
      "/coat.webp",
      "/coat.webp",
      "/coat.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "navy", color: "bg-blue-900" },
      { name: "brown", color: "bg-amber-800" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    stockStatus: "In Stock",
    category: "Clothing",
  },
  2: {
    id: 2,
    name: "Gucci duffle bag",
    price: 150,
    oldPrice: 260,
    discount: "-35%",
    rating: 4,
    reviews: 75,
    description:
      "Luxurious Gucci duffle bag crafted from premium leather. Perfect for travel or daily use with spacious interior and elegant design.",
    images: [
      "/bag.webp",
      "/bag.webp",
      "/bag.webp",
      "/bag.webp",
      "/bag.webp",
    ],
    colors: [
      { name: "brown", color: "bg-amber-800" },
      { name: "black", color: "bg-gray-800" },
    ],
    sizes: ["One Size"],
    stockStatus: "Low Stock",
    category: "Accessories",
  },
  3: {
    id: 3,
    name: "RGB liquid CPU Cooler",
    price: 370,
    oldPrice: 400,
    discount: "-30%",
    rating: 5,
    reviews: 99,
    description:
      "Advanced RGB liquid CPU cooler with superior cooling performance. Features customizable lighting and quiet operation for gaming setups.",
    images: [
      "/headphones.webp",
      "/headphones.webp",
      "/headphones.webp",
      "/headphones.webp",
      "/headphones.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "white", color: "bg-white border" },
    ],
    sizes: ["120mm", "140mm", "240mm"],
    stockStatus: "In Stock",
    category: "Electronics",
  },
  4: {
    id: 4,
    name: "Small BookSelf",
    price: 375,
    oldPrice: 400,
    discount: "-25%",
    rating: 4,
    reviews: 58,
    description:
      "Compact wooden bookshelf perfect for small spaces. Sturdy construction with multiple shelves for books and decorative items.",
    images: [
      "/bookshelf.webp",
      "/bookshelf.webp",
      "/bookshelf.webp",
      "/bookshelf.webp",
      "/bookshelf.webp",
    ],
    colors: [
      { name: "brown", color: "bg-amber-800" },
      { name: "white", color: "bg-white border" },
      { name: "black", color: "bg-gray-800" },
    ],
    sizes: ["Small", "Medium", "Large"],
    stockStatus: "In Stock",
    category: "Furniture",
  },
  5: {
    id: 5,
    name: "S-Series Comfort Chair",
    price: 375,
    oldPrice: 400,
    discount: "-25%",
    rating: 4,
    reviews: 58,
    description:
      "Ergonomic office chair designed for maximum comfort during long working hours. Features adjustable height and lumbar support.",
    images: [
      "/chair.webp",
      "/chair.webp",
      "/chair.webp",
      "/chair.webp",
      "/chair.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "gray", color: "bg-gray-500" },
      { name: "blue", color: "bg-blue-600" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Furniture",
  },
  6: {
    id: 6,
    name: "PlayStation 5",
    price: 499,
    oldPrice: 590,
    discount: "-15%",
    rating: 5,
    reviews: 120,
    description:
      "Next-generation gaming console with ultra-fast SSD and ray tracing support. Experience gaming like never before with 4K graphics.",
    images: [
      "/playstation.webp",
      "/playstation.webp",
      "/playstation.webp",
      "/playstation.webp",
      "/playstation.webp",
    ],
    colors: [{ name: "white", color: "bg-white border" }],
    sizes: ["Standard", "Digital Edition"],
    stockStatus: "In Stock",
    category: "Gaming",
  },
  7: {
    id: 7,
    name: "Women's Collections",
    price: 199,
    oldPrice: 249,
    discount: "-20%",
    rating: 4,
    reviews: 98,
    description:
      "Elegant women's fashion collection featuring the latest trends and premium quality materials. Perfect for any occasion.",
    images: [
      "/womenCollections.webp",
      "/womenCollections.webp",
      "/womenCollections.webp",
      "/womenCollections.webp",
      "/womenCollections.webp",
    ],
    colors: [
      { name: "pink", color: "bg-pink-400" },
      { name: "black", color: "bg-gray-800" },
      { name: "white", color: "bg-white border" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    stockStatus: "In Stock",
    category: "Fashion",
  },
  8: {
    id: 8,
    name: "Amazon Wireless Speakers",
    price: 99,
    oldPrice: 110,
    discount: "-10%",
    rating: 4,
    reviews: 45,
    description:
      "High-quality wireless speakers with crystal clear sound and deep bass. Perfect for home entertainment and outdoor activities.",
    images: [
      "/speakers.webp",
      "/speakers.webp",
      "/speakers.webp",
      "/speakers.webp",
      "/speakers.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "blue", color: "bg-blue-600" },
    ],
    sizes: ["Compact", "Standard", "Large"],
    stockStatus: "Low Stock",
    category: "Electronics",
  },
  9: {
    id: 9,
    name: "GUCCI INTENSE OUD EDP",
    price: 150,
    oldPrice: 200,
    discount: "-25%",
    rating: 5,
    reviews: 62,
    description:
      "Luxurious fragrance with intense oud notes. A sophisticated scent that leaves a lasting impression with its rich and complex aroma.",
    images: [
      "/perfume.webp",
      "/perfume.webp",
      "/perfume.webp",
      "/perfume.webp",
      "/perfume.webp",
    ],
    colors: [{ name: "gold", color: "bg-yellow-600" }],
    sizes: ["50ml", "100ml", "150ml"],
    stockStatus: "In Stock",
    category: "Beauty",
  },
  10: {
    id: 10,
    name: "JBL_BOOMBOX",
    price: 150,
    oldPrice: 200,
    discount: "-25%",
    rating: 5,
    reviews: 62,
    description:
      "Powerful portable speaker with massive sound and powerful bass. Perfect for parties and outdoor adventures with long battery life.",
    images: [
      "/JBL_BOOMBOX.webp",
      "/JBL_BOOMBOX.webp",
      "/JBL_BOOMBOX.webp",
      "/JBL_BOOMBOX.webp",
      "/JBL_BOOMBOX.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "blue", color: "bg-blue-600" },
      { name: "red", color: "bg-red-600" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Electronics",
  },
  11: {
    id: 11,
    name: "Breed Dry Dog Food",
    price: 120,
    oldPrice: 160,
    discount: "-40%",
    rating: 4,
    reviews: 88,
    description:
      "Nutritious dry dog food, specially formulated for various breeds. Promotes healthy digestion and a shiny coat.",
    images: [
      "/dogfood.webp",
      "/dogfood.webp",
      "/dogfood.webp",
      "/dogfood.webp",
      "/dogfood.webp",
    ],
    colors: [{ name: "brown", color: "bg-amber-800" }],
    sizes: ["1kg", "5kg", "10kg"],
    stockStatus: "In Stock",
    category: "Pet Supplies",
  },
  12: {
    id: 12,
    name: "CANON EOS DSLR Camera",
    price: 150,
    oldPrice: 260,
    discount: "-35%",
    rating: 4,
    reviews: 75,
    description:
      "High-performance DSLR camera for professional-grade photography. Features advanced autofocus and stunning image quality.",
    images: [
      "/camera.webp",
      "/camera.webp",
      "/camera.webp",
      "/camera.webp",
      "/camera.webp",
    ],
    colors: [{ name: "black", color: "bg-gray-800" }],
    sizes: ["Standard"],
    stockStatus: "Low Stock",
    category: "Electronics",
  },
  13: {
    id: 13,
    name: "ASUS FHD Gaming Laptop",
    price: 370,
    oldPrice: 400,
    discount: "-30%",
    rating: 5,
    reviews: 99,
    description:
      "Powerful gaming laptop with full HD display and high-end graphics card. Perfect for immersive gaming experiences.",
    images: [
      "/laptop.webp",
      "/laptop.webp",
      "/laptop.webp",
      "/laptop.webp",
      "/laptop.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "gray", color: "bg-gray-500" },
    ],
    sizes: ["15.6 inch", "17.3 inch"],
    stockStatus: "In Stock",
    category: "Electronics",
  },
  14: {
    id: 14,
    name: "Curology Product Set",
    price: 375,
    oldPrice: 400,
    discount: "-25%",
    rating: 4,
    reviews: 58,
    description:
      "Customized skincare set designed to address specific skin concerns. Includes cleanser, treatment, and moisturizer for a complete routine.",
    images: [
      "/cream.webp",
      "/cream.webp",
      "/cream.webp",
      "/cream.webp",
      "/cream.webp",
    ],
    colors: [{ name: "white", color: "bg-white border" }],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Beauty",
  },
  15: {
    id: 15,
    name: "Kids Electric Car",
    price: 375,
    oldPrice: 400,
    discount: "-25%",
    rating: 4,
    reviews: 58,
    description:
      "Fun and safe electric car for kids, with realistic features and remote control option. Perfect for outdoor play.",
    images: [
      "/car.webp",
      "/car.webp",
      "/car.webp",
      "/car.webp",
      "/car.webp",
    ],
    colors: [
      { name: "red", color: "bg-red-600" },
      { name: "blue", color: "bg-blue-600" },
      { name: "white", color: "bg-white border" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Toys",
  },
  16: {
    id: 16,
    name: "Jr. Zoom Soccer Cleats",
    price: 375,
    oldPrice: 400,
    discount: "-25%",
    rating: 4,
    reviews: 58,
    description:
      "High-performance soccer cleats for junior players. Designed for speed, agility, and optimal ball control on the field.",
    images: [
      "/shoes.webp",
      "/shoes.webp",
      "/shoes.webp",
      "/shoes.webp",
      "/shoes.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "white", color: "bg-white border" },
      { name: "red", color: "bg-red-600" },
    ],
    sizes: ["Kids 1", "Kids 2", "Kids 3"],
    stockStatus: "Low Stock",
    category: "Sports",
  },
  17: {
    id: 17,
    name: "GP11 Shooter USB Gamepad",
    price: 375,
    oldPrice: 400,
    discount: "-25%",
    rating: 4,
    reviews: 58,
    description:
      "Ergonomic USB gamepad for PC and console gaming. Features precise controls and comfortable grip for extended play sessions.",
    images: [
      "/g-black.webp",
      "/g-black.webp",
      "/g-black.webp",
      "/g-black.webp",
      "/g-black.webp",
    ],
    colors: [{ name: "black", color: "bg-gray-800" }],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Gaming",
  },
  18: {
    id: 18,
    name: "Quilted Satin Jacket",
    price: 375,
    oldPrice: 400,
    discount: "-25%",
    rating: 4,
    reviews: 58,
    description:
      "Stylish quilted satin jacket for a chic and comfortable look. Perfect for layering in transitional weather.",
    images: [
      "/jacket.webp",
      "/jacket.webp",
      "/jacket.webp",
      "/jacket.webp",
      "/jacket.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "green", color: "bg-emerald-600" },
    ],
    sizes: ["S", "M", "L", "XL"],
    stockStatus: "In Stock",
    category: "Clothing",
  },
  19: {
    id: 19,
    name: "The north coat",
    price: 120,
    oldPrice: 160,
    discount: "-40%",
    rating: 4,
    reviews: 88,
    description:
      "High-quality north face coat perfect for winter weather. Made with premium materials and designed for ultimate comfort and warmth.",
    images: [
      "/coat.webp",
      "/coat.webp",
      "/coat.webp",
      "/coat.webp",
      "/coat.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "navy", color: "bg-blue-900" },
      { name: "brown", color: "bg-amber-800" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    stockStatus: "In Stock",
    category: "Clothing",
  },
  20: {
    id: 20,
    name: "Gucci duffle bag",
    price: 150,
    oldPrice: 260,
    discount: "-35%",
    rating: 4,
    reviews: 75,
    description:
      "Luxurious Gucci duffle bag crafted from premium leather. Perfect for travel or daily use with spacious interior and elegant design.",
    images: [
      "/bag.webp",
      "/bag.webp",
      "/bag.webp",
      "/bag.webp",
      "/bag.webp",
    ],
    colors: [
      { name: "brown", color: "bg-amber-800" },
      { name: "black", color: "bg-gray-800" },
    ],
    sizes: ["One Size"],
    stockStatus: "Low Stock",
    category: "Accessories",
  },
  21: {
    id: 21,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    discount: "-40%",
    rating: 4,
    reviews: 88,
    description:
      "Ergonomic gamepad for immersive gaming. Features responsive buttons and comfortable grip for long hours of play.",
    images: [
      "/g-colored.webp",
      "/g-colored.webp",
      "/g-colored.webp",
      "/g-colored.webp",
      "/g-colored.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "red", color: "bg-red-600" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Gaming",
  },
  22: {
    id: 22,
    name: "AK-900 Wired Keyboard",
    price: 950,
    oldPrice: 1160,
    discount: "-35%",
    rating: 4,
    reviews: 75,
    description:
      "Durable wired keyboard with responsive keys and ergonomic design. Ideal for gaming and professional use.",
    images: [
      "/keyboard.webp",
      "/keyboard.webp",
      "/keyboard.webp",
      "/keyboard.webp",
      "/keyboard.webp",
    ],
    colors: [{ name: "black", color: "bg-gray-800" }],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Electronics",
  },
  23: {
    id: 23,
    name: "IPS LCD Gaming Monitor",
    price: 370,
    oldPrice: 400,
    discount: "-30%",
    rating: 5,
    reviews: 99,
    description:
      "High-refresh-rate IPS LCD gaming monitor with vibrant colors and wide viewing angles. Enhances your gaming experience.",
    images: [
      "/tv.webp",
      "/tv.webp",
      "/tv.webp",
      "/tv.webp",
      "/tv.webp",
    ],
    colors: [{ name: "black", color: "bg-gray-800" }],
    sizes: ["24 inch", "27 inch", "32 inch"],
    stockStatus: "In Stock",
    category: "Electronics",
  },
  24: {
    id: 24,
    name: "S-Series Comfort Chair",
    price: 375,
    oldPrice: 400,
    discount: "-25%",
    rating: 4,
    reviews: 58,
    description:
      "Ergonomic office chair designed for maximum comfort during long working hours. Features adjustable height and lumbar support.",
    images: [
      "/chair.webp",
      "/chair.webp",
      "/chair.webp",
      "/chair.webp",
      "/chair.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "gray", color: "bg-gray-500" },
      { name: "blue", color: "bg-blue-600" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Furniture",
  },
  25: {
    id: 25,
    name: "Small Bookshelf",
    price: 360,
    oldPrice: 504,
    discount: "-60%",
    rating: 5,
    reviews: 123,
    description:
      "Compact wooden bookshelf perfect for small spaces. Sturdy construction with multiple shelves for books and decorative items.",
    images: [
      "/bookshelf.webp",
      "/bookshelf.webp",
      "/bookshelf.webp",
      "/bookshelf.webp",
      "/bookshelf.webp",
    ],
    colors: [
      { name: "brown", color: "bg-amber-800" },
      { name: "white", color: "bg-white border" },
      { name: "black", color: "bg-gray-800" },
    ],
    sizes: ["Small", "Medium", "Large"],
    stockStatus: "Low Stock",
    category: "Furniture",
  },
  26: {
    id: 26,
    name: "RGB liquid CPU Cooler",
    price: 160,
    oldPrice: 234,
    discount: "-20%",
    rating: 3,
    reviews: 233,
    description:
      "Advanced RGB liquid CPU cooler with superior cooling performance. Features customizable lighting and quiet operation for gaming setups.",
    images: [
      "/headphones.webp",
      "/headphones.webp",
      "/headphones.webp",
      "/headphones.webp",
      "/headphones.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "white", color: "bg-white border" },
    ],
    sizes: ["120mm", "140mm", "240mm"],
    stockStatus: "In Stock",
    category: "Electronics",
  },
  27: {
    id: 27,
    name: "ASUS FHD Gaming Laptop",
    price: 700,
    oldPrice: 1000,
    discount: "-30%",
    rating: 3,
    reviews: 99,
    description:
      "Powerful gaming laptop with full HD display and high-end graphics card. Perfect for immersive gaming experiences.",
    images: [
      "/laptop.webp",
      "/laptop.webp",
      "/laptop.webp",
      "/laptop.webp",
      "/laptop.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "gray", color: "bg-gray-500" },
    ],
    sizes: ["15.6 inch", "17.3 inch"],
    stockStatus: "In Stock",
    category: "Electronics",
  },
  28: {
    id: 28,
    name: "Jr. Zoom Soccer Cleats",
    price: 80,
    oldPrice: 100,
    discount: "-30%",
    rating: 4,
    reviews: 332,
    description:
      "High-performance soccer cleats for junior players. Designed for speed, agility, and optimal ball control on the field.",
    images: [
      "/shoes.webp",
      "/shoes.webp",
      "/shoes.webp",
      "/shoes.webp",
      "/shoes.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "white", color: "bg-white border" },
      { name: "red", color: "bg-red-600" },
    ],
    sizes: ["Kids 1", "Kids 2", "Kids 3"],
    stockStatus: "In Stock",
    category: "Sports",
  },
  29: {
    id: 29,
    name: "CANON EOS DSLR Camera",
    price: 500,
    oldPrice: 600,
    discount: "-12%",
    rating: 4,
    reviews: 132,
    description:
      "High-performance DSLR camera for professional-grade photography. Features advanced autofocus and stunning image quality.",
    images: [
      "/camera.webp",
      "/camera.webp",
      "/camera.webp",
      "/camera.webp",
      "/camera.webp",
    ],
    colors: [{ name: "black", color: "bg-gray-800" }],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Electronics",
  },
  30: {
    id: 30,
    name: "infinix Zero Ultra",
    price: 950,
    oldPrice: 1190,
    discount: "-20%",
    rating: 5,
    reviews: 142,
    description:
      "The infinix Zero Ultra features a sleek design, high-speed performance, and an amazing triple-camera system for pro-level photography.",
    images: [
      "/phone1.webp",
      "/phone1.webp",
      "/phone1.webp",
      "/phone1.webp",
      "/phone1.webp",
    ],
    colors: [
      { name: "phantom gray", color: "bg-gray-700" },
      { name: "phantom violet", color: "bg-purple-500" },
      { name: "phantom pink", color: "bg-pink-400" },
    ],
    sizes: ["128GB", "256GB", "512GB"],
    stockStatus: "In Stock",
    category: "Smartphones",
  },

  31: {
    id: 31,
    name: "Samsung Galaxy Z",
    price: 1250,
    oldPrice: 1470,
    discount: "-15%",
    rating: 5,
    reviews: 312,
    description:
      "Experience the future with the foldable Samsung Galaxy Z. Compact design meets powerful performance in this revolutionary phone.",
    images: [
      "/phone2.webp",
      "/phone2.webp",
      "/phone2.webp",
      "/phone2.webp",
      "/phone2.webp",
    ],
    colors: [
      { name: "black", color: "bg-black" },
      { name: "green", color: "bg-green-600" },
      { name: "silver", color: "bg-gray-300" },
    ],
    sizes: ["256GB", "512GB"],
    stockStatus: "In Stock",
    category: "Smartphones",
  },

  32: {
    id: 32,
    name: "Apple iPhone 14 Pro",
    price: 820,
    oldPrice: 1000,
    discount: "-18%",
    rating: 4,
    reviews: 98,
    description:
      "The iPhone 14 Pro comes with a powerful A16 Bionic chip, improved battery life, and a new 48MP main camera for stunning shots.",
    images: [
      "/phone3.webp",
      "/phone3.webp",
      "/phone3.webp",
      "/phone3.webp",
      "/phone3.webp",
    ],
    colors: [
      { name: "deep purple", color: "bg-purple-900" },
      { name: "space black", color: "bg-gray-900" },
      { name: "silver", color: "bg-gray-300" },
    ],
    sizes: ["128GB", "256GB", "512GB", "1TB"],
    stockStatus: "In Stock",
    category: "Smartphones",
  },
  33: {
    id: 33,
    name: "NVIDIA GeForce RTX 4090",
    price: 2200,
    oldPrice: 2500,
    discount: "-12%",
    rating: 5,
    reviews: 412,
    description:
      "Experience unparalleled performance with the RTX 4090. Built for extreme gaming and rendering, with ray tracing and DLSS 3 support.",
    images: [
      "/pc1.webp",
      "/pc1.webp",
      "/pc1.webp",
      "/pc1.webp",
      "/pc1.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-900" },
      { name: "silver", color: "bg-gray-300" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Graphics Cards",
  },

  34: {
    id: 34,
    name: "AMD Radeon RX 7900 XTX",
    price: 1800,
    oldPrice: 2000,
    discount: "-10%",
    rating: 4,
    reviews: 285,
    description:
      "Unlock next-gen gaming with the Radeon RX 7900 XTX. Designed for high-resolution gaming and professional creative workloads.",
    images: [
      "/pc2.webp",
      "/pc2.webp",
      "/pc2.webp",
      "/pc2.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "red", color: "bg-red-700" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Graphics Cards",
  },

  35: {
    id: 35,
    name: "Apple Watch Series 9",
    price: 399,
    oldPrice: 470,
    discount: "-15%",
    rating: 5,
    reviews: 198,
    description:
      "Stay connected, healthy, and fit with the Apple Watch Series 9. Advanced health features, stunning display, and seamless iPhone integration.",
    images: [
      "/watch.webp",
      "/watch.webp",
      "/watch.webp",
      "/watch.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "silver", color: "bg-gray-300" },
      { name: "red", color: "bg-red-600" },
    ],
    sizes: ["40mm", "44mm"],
    stockStatus: "In Stock",
    category: "Smart Watch",
  },
  36: {
    id: 36,
    name: "Samsung Galaxy Watch 6",
    price: 299,
    oldPrice: 375,
    discount: "-20%",
    rating: 4,
    reviews: 112,
    description:
      "Track your health and performance with the Galaxy Watch 6. Sleek design, powerful features, and seamless Galaxy ecosystem integration.",
    images: [
      "/watch1.webp",
      "/watch1.webp",
      "/watch1.webp",
      "/watch1.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "silver", color: "bg-gray-300" },
    ],
    sizes: ["42mm", "46mm"],
    stockStatus: "In Stock",
    category: "Smart Watch",
  },
  37: {
    id: 37,
    name: "Fitbit Versa 4",
    price: 169,
    oldPrice: 210,
    discount: "-18%",
    rating: 4,
    reviews: 76,
    description:
      "Stay motivated and on track with Fitbit Versa 4. Lightweight design, fitness tracking, and great battery life for daily performance.",
    images: [
      "/watch2.webp",
      "/watch2.webp",
      "/watch2.webp",
      "/watch2.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "blue", color: "bg-blue-500" },
    ],
    sizes: ["Small", "Large"],
    stockStatus: "In Stock",
    category: "Smart Watch",
  },
   38: {
    id: 38,
    name: "Canon EOS 90D DSLR",
    price: 950,
    oldPrice: 1050,
    discount: "-10%",
    rating: 5,
    reviews: 182,
    description:
      "Capture stunning images with the Canon EOS 90D. A powerful DSLR with fast autofocus, 32.5 MP sensor, and 4K video capabilities.",
    images: [
      "/camera1.webp",
      "/camera1.webp",
      "/camera1.webp",
    ],
    colors: [{ name: "black", color: "bg-gray-800" }],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Cameras",
  },
   39: {
    id: 39,
    name: "Sony Alpha a7 III",
    price: 1199,
    oldPrice: 1350,
    discount: "-12%",
    rating: 4,
    reviews: 145,
    description:
      "The Sony Alpha a7 III is a full-frame mirrorless camera with excellent low-light performance and 5-axis stabilization. Ideal for photographers and videographers.",
    images: [
      "/camera3.webp",
      "/camera3.webp",
      "/camera3.webp",
    ],
    colors: [{ name: "black", color: "bg-gray-800" }],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Cameras",
  },
   40: {
    id: 40,
    name: "Nikon Z6 II Mirrorless",
    price: 1100,
    oldPrice: 1290,
    discount: "-15%",
    rating: 4,
    reviews: 102,
    description:
      "The Nikon Z6 II offers outstanding image quality, dual processors, and superb autofocus. Perfect for hybrid shooters who want both stills and video.",
    images: [
      "/camera2.webp",
      "/camera2.webp",
      "/camera2.webp",
    ],
    colors: [{ name: "black", color: "bg-gray-800" }],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Cameras",
  },


  41: {
    id: 41,
    name: "Sony WH-1000XM4",
    price: 300,
    oldPrice: 400,
    discount: "-25%",
    rating: 5,
    reviews: 450,
    description:
      "Industry-leading noise cancellation headphones with up to 30 hours of battery life, exceptional sound quality, and touch sensor controls.",
    images: [
      "/headphone1.webp",
      "/headphone1.webp",
      "/headphone1.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "silver", color: "bg-gray-300" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Headphones",
  },
   42: {
    id: 42,
    name: "Bose QuietComfort 45",
    price: 280,
    oldPrice: 350,
    discount: "-20%",
    rating: 4,
    reviews: 315,
    description:
      "Comfortable over-ear headphones with deep, clear sound and advanced noise cancellation. Ideal for travel, work, and everyday use.",
    images: [
      "/headphone2.webp",
      "/headphone2.webp",
      "/headphone2.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "white", color: "bg-white border" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Headphones",
  },
   43: {
    id: 43,
    name: "Apple AirPods Max",
    price: 490,
    oldPrice: 580,
    discount: "-15%",
    rating: 4,
    reviews: 220,
    description:
      "Premium over-ear headphones by Apple, featuring spatial audio, active noise cancellation, and an ultra-low distortion driver.",
    images: [
      "/headphone3.webp",
      "/headphone3.webp",
      "/headphone3.webp",
    ],
    colors: [
      { name: "space gray", color: "bg-gray-700" },
      { name: "sky blue", color: "bg-blue-300" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Headphones",
  },
   44: {
    id: 44,
    name: "Razer BlackShark V2",
    price: 110,
    oldPrice: 137,
    discount: "-20%",
    rating: 5,
    reviews: 190,
    description:
      "Razer's high-performance esports headset featuring advanced surround sound, titanium drivers, and a detachable mic.",
    images: [
      "/gaming1.webp",
      "/gaming1.webp",
      "/gaming1.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "green", color: "bg-green-600" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Gaming",
  },
   45: {
    id: 45,
    name: "Logitech G502 HERO",
    price: 45,
    oldPrice: 55,
    discount: "-18%",
    rating: 4,
    reviews: 250,
    description:
      "High-precision gaming mouse with customizable buttons, RGB lighting, and advanced HERO sensor for competitive gamers.",
    images: [
      "/gaming2.webp",
      "/gaming2.webp",
      "/gaming2.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-800" },
      { name: "blue", color: "bg-blue-600" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Gaming",
  },
   46: {
    id: 46,
    name: "Redragon K552 Mechanical Keyboard",
    price: 60,
    oldPrice: 85,
    discount: "-30%",
    rating: 4,
    reviews: 312,
    description:
      "Compact mechanical gaming keyboard with red switches, RGB lighting, and durable metal construction for serious gamers.",
    images: [
      "/gaming3.webp",
      "/gaming3.webp",
      "/gaming3.webp",
    ],
    colors: [
      { name: "black", color: "bg-gray-900" },
      { name: "red", color: "bg-red-600" },
    ],
    sizes: ["Standard"],
    stockStatus: "In Stock",
    category: "Gaming",
  },
  
  

  
};

export default productsData;
